#ifndef NOVATEL_GPS_DRIVER_COMMON_PARAM_H
#define NOVATEL_GPS_DRIVER_COMMON_PARAM_H
#include <string>

namespace novatel_gps_driver {

const std::string INS_STATUS[] = {"INS_INACTIVE",
                                  "INS_ALIGNING",
                                  "INS_HIGH_VARIANCE",
                                  "INS_SOLUTION_GOOD",
                                  "RESERVED",
                                  "RESERVED",
                                  "INS_SOLUTION_FREE",
                                  "INS_ALIGNMENT_COMPLETE",
                                  "DETERMINING_ORIENTATION",
                                  "WAITING_INITIALPOS",
                                  "WAITING_AZIMUTH",
                                  "INITIALIZING_BASES",
                                  "MOTION_DETECT"};

const std::string RTK_POSITION_TYPES[] = {"NONE",
                                          "FIXED",
                                          "FIXEDHEIGHT",
                                          "",
                                          "FLOATCONV",
                                          "WIDELANE",
                                          "NARROWLANE",
                                          "",
                                          "DOPPLER_VELOCITY",
                                          "",
                                          "",
                                          "",
                                          "",
                                          "",
                                          "",
                                          "",
                                          "SINGLE",
                                          "PSRDIFF",
                                          "WAAS",
                                          "PROPAGATED",
                                          "OMNISTAR",
                                          "",
                                          "",
                                          "",
                                          "",
                                          "",
                                          "",
                                          "",
                                          "",
                                          "",
                                          "",
                                          "",
                                          "L1_FLOAT",
                                          "IONOFREE_FLOAT",
                                          "NARROW_FLOAT",
                                          "",
                                          "",
                                          "",
                                          "",
                                          "",
                                          "",
                                          "",
                                          "",
                                          "",
                                          "",
                                          "",
                                          "",
                                          "",
                                          "L1_INT",
                                          "WIDE_INT",
                                          "NARROW_INT",
                                          "RTK_DIRECT_INS",
                                          "INS_SBAS",
                                          "INS_PSRSP",
                                          "INS_PSRDIFF",
                                          "INS_RTKFLOAT",
                                          "INS_RTKFIXED",
                                          "INS_OMNISTAR",
                                          "INS_OMNISTAR_HP",
                                          "INS_OMNISTAR_XP",
                                          "",
                                          "",
                                          "",
                                          "",
                                          "OMNISTAR_HP",
                                          "OMNISTAR_XP",
                                          "",
                                          "",
                                          "PPP_CONVERGING",
                                          "PPP",
                                          "",
                                          "",
                                          "",
                                          "INS_PPP_CONVERGING",
                                          "INS_PPP"};
}  // namespace novatel_gps_driver

#endif